### ISSUE TITLE
nearest_stations() distance info

### ISSUE THREAD

**Issue by pssguy** [ropensci/GSODR#24]
Thanks for doing this
Couple of points

1) There does not appear to be any difference in time taken to return a list of stations frrom a distance of 10 or 100 km . In my test 4 are returned in case 1 and 107 in case 2. both take around 10 secs. Is this just the way it is or could the former be speeded up

2) The r code implies that you could return a distance (miles=FALSE). Can you set an option so that distance could also be returned as station id (presumably as a data.frame)so that the nearest or nearest 5,say, could be identified for further processing

thank

**Comment by adamhsparks** [comment]
To point 1, the time it takes is mainly a function of fetching data from the NCEI server that has the list of stations. The calculation of the nearest stations whether 4 or 107 are returned is pretty fast itself, which is why you notice that the amount of time it takes does not matter whether it's a large or small number of stations returned. The only way to make this function any faster is to include the stations file list (isd-history.csv) in the package, which I had initially done, but it does change more frequently than I update the package. So I've elected to fetch the file for every time the isd-history.csv file is requested.

However, I have recently written another R package that takes advantage of caching files, I should implement that here so that it only fetches the stations list file once per R session, that would make repeated use faster.

About point two, I don't quite understand your question here. Could you explain a bit further what you desire the output to be? The portion you refer to simply says that I want the Great circle distance returned in kilometres not in miles, `?fields::rdist.earth`.

**Comment by pssguy** [comment]
Thanks for swift response

1. I'm looking at using the package in an interactive web app so any delay is off putting. Notifying users that after first interaction the delay would be minimal would be a great help. I guess an alternative would be to load the isd-history.csv in the code and accept that it is not always up to date

2. OK I misunderstood (miles=FALSE).  nearest_stations() returns a vector of station ids. Could it, alternatively, return a data.frame of station_id and distance from the lat/lon entered. So I could then do further processing on the nearest n stations

**Comment by adamhsparks** [comment]
Nice! I'm excited to see that it's getting some use and am happy to do what I can to improve it.

1. I've done some research this morning. I think I can include the file as external data and offer the user the ability to update this external data. I think that's the most useful approach. I'll look into this further.

2. I'll look into that after the isd-stations.csv file caching/distribution.

**Comment by adamhsparks** [comment]
I've just committed changes to the devel branch that have a test of the functionality now to update the external data and distribute a version of the "isd-history.csv" data with _GSODR_, which does mean the station distances are returned more quickly: https://github.com/ropensci/GSODR/commit/5e7562aabcc34796c64e4094cd40390d5edbd740

**Comment by adamhsparks** [comment]
I've added an internal database of the station list and metadata now to the version here on GitHub if you'd like to give it a go?

**Comment by adamhsparks** [comment]
This feature is now available from v1.0.3 on CRAN. Closing this, feel free to reopen if you have further comments or questions about it.
